### ISSUE TITLE
Error creating dynamodb table without StreamEnabled option

### ISSUE THREAD

**Issue by alexzelenuyk** [99xt/serverless-dynamodb-local#100]
Hi, there

I have a problem starting sls offline with dynamodb-local when i setup dynamodb stream.
Error:
```
$ SLS_DEBUG=* $(yarn bin)/sls offline start
[offline] Invalidating cache...
[offline] Loading handler... (/project/src/functions/store)
Dynamodb Local Started, Visit: http://localhost:8000/shell
Serverless: DynamoDB - Error -

  Validation Exception -----------------------------------

     Stream StreamEnabled was null

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

ValidationException: Stream StreamEnabled was null
    at Request.extractError (/project/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/project/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/project/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/project/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/project/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/project/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /project/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/project/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/project/node_modules/aws-sdk/lib/request.js:675:12)
    at Request.callListeners (/project/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/project/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/project/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/project/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/project/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /project/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/project/node_modules/aws-sdk/lib/request.js:38:9)
From previous event:
    at ServerlessDynamodbLocal.createTable (/project/node_modules/serverless-dynamodb-local/index.js:195:16)
    at BbPromise.each (/project/node_modules/serverless-dynamodb-local/index.js:122:55)
From previous event:
    at ServerlessDynamodbLocal.migrateHandler (/project/node_modules/serverless-dynamodb-local/index.js:122:26)
    at BbPromise.resolve.then (/project/node_modules/serverless-dynamodb-local/index.js:157:45)
From previous event:
    at ServerlessDynamodbLocal.startHandler (/project/node_modules/serverless-dynamodb-local/index.js:157:10)
    at BbPromise.reduce (/project/node_modules/serverless/lib/classes/PluginManager.js:210:55)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at PluginManager.invoke (/project/node_modules/serverless/lib/classes/PluginManager.js:210:22)
    at PluginManager.run (/project/node_modules/serverless/lib/classes/PluginManager.js:225:17)
    at Serverless.run (/project/node_modules/serverless/lib/Serverless.js:97:31)
    at serverless.init.then (/project/node_modules/serverless/bin/serverless:23:50)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       7.2.1
     Serverless Version: 1.10.2
```

My resource specification from `serverless.yml`:
```yaml
resources:
  Resources:
    Table:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table}
        AttributeDefinitions:
          ...
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
```

When i configure `StreamEnabled: true` - it works, but breaks deploy to AWS with error:
```
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: Notifications
     - Encountered unsupported property StreamEnabled.
```
as `StreamEnabled` options seems to be not supported by CloudFormation [doc](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-streamspecification.html)

**Comment by iadknet** [comment]
I am also having this issue

**Comment by rehrumesh** [comment]
Fixed from #102

**Comment by rehrumesh** [comment]
@daneprime8 can you try using `serverless-dynamodb-local version 0.2.33`? let us know what happens.

**Comment by kdby-io** [comment]
I am using 0.2.35. But this issue is not fixed.

**Comment by pq-vbakh** [comment]
Have the same issue

**Comment by pianomansam** [comment]
I have `serverless-dynamodb-local` 0.2.38 and am still receiving this issue. It does not appear to be fixed!

One detail to note: It work working fine, but then I installed `serverless-appsync-offline` and that's when I started receiving this issue.

**Comment by lwillmeth** [comment]
This is still broken in 0.2.39.

**Comment by murilloagoncalves** [comment]
Is there any workaround here?

**Comment by quangnhattran** [comment]
Yes, please anybody update on this problem?

**Comment by TomasMorton** [comment]
We still don't have a solution to this?? It's been 3 years...
