### ISSUE TITLE
Seed is not working in release

### ISSUE THREAD

**Issue by nenti** [99xt/serverless-dynamodb-local#85]
The NPM Release doesn't include Seed functionality.

**Comment by mhrisse** [comment]
Same problem.

```    
"serverless-dynamodb-client": "0.0.2",
"serverless-dynamodb-local": "0.2.19",
"serverless-offline": "3.13.0",
```

running ```serverless@1.9```

I really like this plugin and it is tremendously useful, but In combination with https://github.com/99xt/serverless-dynamodb-local/issues/83 I have to say stability is becoming a little bit problematic. Such basic features need to be tested.

How can I help?

**Comment by AshanFernando** [comment]
@nenti  I have updated the latest version to NPM registry. Thanks for pointing it out.

To improve stability, I feel one of the most important things missing is automated Unit Testing. @mhrisse What do you think?

**Comment by darthtrevino** [comment]
This looks resolved now

**Comment by mhrisse** [comment]
@darthtrevino @nenti @nielsgl I have tried `0.2.20`over `0.2.19`and running `0.2.19` works, but does not seed. However, the just released `0.2.20` hangs the whole server. (same code otherwise). Once I revert, I get the `0.2.19`behaviour again.

```0.2.20``` behaviour, config as above:
```
Serverless: GET /v1/dealers (λ: dealers-read)
Serverless: The first request might take a few extra seconds
Serverless: 
Serverless: Replying timeout after 30000ms
```

**Comment by darthtrevino** [comment]
Is serverless-offline up to date?

On Mon, Mar 27, 2017, 8:33 AM Matthias H. Risse <notifications@github.com>
wrote:

@nenti <https://github.com/nenti> @nielsgl <https://github.com/nielsgl> I
have tried 0.2.20over 0.2.19and while running 0.2.19 works, but does not
seed. However, the just released 0.2.20 hangs the whole server. (same code
otherwise).

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/99xt/serverless-dynamodb-local/issues/85#issuecomment-289394975>,
or mute the thread

**Comment by nenti** [comment]
@mhrisse This is related to the issue with `0.2.20` not automatically starting dynamodb on `serverless offline` command. Try to use `serverless offline start` (with **start**) until the issue is resolved. 

It is currently discussed in #90 

Is anyone actually looking into this or should we create a separate issue for this @darthtrevino

**Comment by mhrisse** [comment]
Hi! Sorry for the delay. Yes, it's all up to date. Seeding still does not work, but it tells me it is doing it. `Table creation completed for table: mytable`, but no data in the db confirmed via dyno shell.
Maybe worth reopening this ticket?

Sometimes, when I terminate with ctrl+c it tells me DynamoDB has an issue starting (which is odd in itself), sometimes not.

**Comment by nielsgl** [comment]
@mhrisse can you post your serverless.yml and seed files? It's working for me so I can compare our configs.

**Comment by darthtrevino** [comment]
Are you using a seed argument? You need to specify the seeding categories via the CLI. 
e.g. `sls offline start --seed=domain_data,test_data`

**Comment by cdelgadob** [comment]
Hey, just opened the same issue, sorry didn't see this before. Issue #121

It is still happening in version 0.2.24

Do you have any workaround or other seeding plugin? It would be nice to have one way to seed DynamoDB local or remote.
